paulo@DESKTOP-TH7FC38:~/onix_oac_docker$ cat docker-compose.yml
volumes:
  db_data:

networks:
  onix_network:
    driver: bridge

services:

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - onix_network

  onix_oac:
    container_name: onix_oac
    user: "1000"
    build: ./onix_oac
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./onix_oac/:/var/www/html/
      - ./onix_oac/myapp.conf:/etc/apache2/sites-enabled/myapp.conf
      - ./onix_aso:/var/www/onix_aso/
      - ./php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
    ports:
      - 9000:80
    networks:
      - onix_network
    links:
      - db
      - onix_api

  onix_api:
    container_name: onix_api
    user: "1000"
    build: ./new_structure/
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./new_structure/:/var/www/html/
      - ./new_structure/myapp.conf:/etc/apache2/sites-enabled/myapp.conf
      - ./php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
    ports:
      - 8000:80
      - 8010:8080
    networks:
      - onix_network
    links:
      - db

  db:
    image: mariadb:10.5.19
    restart: "always"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mariadb.cnf:/etc/mysql/mariadb.cnf"
    environment:
      MARIADB_ROOT_PASSWORD: "MIc5nDNmUW"
    ports:
      - "3307:3306"
    networks:
      - onix_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    restart: always
    environment:
      PMA_HOST: "db"
      PMA_ARBITRARY: 1
      PHP_UPLOAD_MAX_FILESIZE: 512M
      PHP_POST_MAX_SIZE: 512M
      UPLOAD_LIMIT: 512M
      PHP_MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 1200
    depends_on:
      - db
    networks:
      - onix_network